### ISSUE TITLE
Gallery with additional filter features

### ISSUE THREAD

**Issue by EyeOfMidas** [libgdx/libgdx-site#10]
I'm debating adding additional features to the now-crowded gallery page. A simple tag filter system, for instance. Developers uploading their game could optionally add "tags" like "3D" "puzzle" or "platformer" and on the gallery page user could filter based on those tags.

I haven't started work on it, but I'd like to know before I start if this is something the libGDX community would be interested in having.

**Comment by crykn** [comment]
No longer a problem since #55.
