### ISSUE TITLE
Use CSS sprites instead of individual images (Minor issue)

### ISSUE THREAD

**Issue by biobob** [libgdx/libgdx-site#3]
First of all, this issue is not critical at all. I'm just a PITA :).

CSS sprites are faster to load because this technique saves HTTP round-trips to server. Even when they run in parallel, their duration may differ. See example:

![responses](https://f.cloud.github.com/assets/1621979/762514/78fc2866-e7e9-11e2-8791-01d9cd4ab484.png)

Moreover it can suppress flickering of menu images after hovering on first try. The browser will display empty space during HTTP communication because highlighted images aren't retrieved ahead.

More about this topic here: http://css-tricks.com/css-sprites/

I understand that editing whole sprite atlas can be difficult when the design will be tuned during iterative enhancements in the future. So I encourage to use tools for this purpose. Open-source project SmartSprites (http://csssprites.org/) is the right choice. You can use individual images in the CSS code and annotate it with simple directives in comments.

During "build" of web page the tool can pack all images into sprite atlases and add correct CSS position shifts automatically. As easy as pie. The real magic happen when you mavenize whole thing.

Maven plugin: https://github.com/carrotsearch/smartsprites
Example project: https://github.com/ljagenow/smartspritesExampleApp/tree/v1.0

**Comment by crykn** [comment]
Closing this due to #55.
